# Generated by Django 5.1.6 on 2025-02-17 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 20, 13, 19, 905187, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
