# Generated by Django 5.1.6 on 2025-02-18 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 4, 58, 39, 1103, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
