# Generated by Django 5.1.6 on 2025-02-21 18:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_barberprofile_dayschedule_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reservation_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='barber_profile',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='appointment date'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 18, 5, 3, 284407, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
