# Generated by Django 5.1.6 on 2025-02-21 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_appointment_reservation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_barber_profile',
            field=models.BooleanField(default=False, verbose_name='has barber profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 19, 33, 22, 769128, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
