# Generated by Django 5.1.6 on 2025-02-21 20:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_has_barber_profile_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayschedule',
            options={'ordering': ['id'], 'verbose_name': 'Day Schedule', 'verbose_name_plural': 'days schedule'},
        ),
        migrations.AlterModelOptions(
            name='offdays',
            options={'ordering': ['id'], 'verbose_name': 'Off Day', 'verbose_name_plural': 'Off Days'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day_schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barberprofile'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[('Sunday', 1), ('Saturday', 2), ('Monday', 3), ('Tuesday', 4), ('Wednesday', 5), ('Thursday', 6), ('Friday', 7)], default=1, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 20, 42, 59, 679726, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AlterModelTable(
            name='dayschedule',
            table='days_schedules',
        ),
        migrations.AlterModelTable(
            name='offdays',
            table='off_days',
        ),
    ]
