# Generated by Django 5.1.6 on 2025-02-21 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_dayschedule_options_alter_offdays_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 20, 50, 17, 771500, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='schedule',
            field=models.ManyToManyField(blank=True, related_name='schedule', to='users.dayschedule'),
        ),
    ]
