# Generated by Django 5.1.6 on 2025-02-21 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_dayschedule_day_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayschedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Sunday', verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 21, 4, 24, 203460, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
