# Generated by Django 5.1.6 on 2025-02-21 21:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_dayschedule_day_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='schedule',
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barberprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 21, 8, 51, 754893, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
