# Generated by Django 5.1.6 on 2025-02-21 21:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_barberprofile_schedule_dayschedule_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(null=True, verbose_name='appointment date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barberprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='certification_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='certification image'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='location',
            field=models.JSONField(null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barberprofile'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], null=True, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='offdays',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.barberprofile'),
        ),
        migrations.AlterField(
            model_name='offdays',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 21, 23, 22, 563890, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
