# Generated by Django 5.1.6 on 2025-02-22 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_barberprofile_user_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='certification_image',
            field=models.ImageField(null=True, upload_to='certifications/', verbose_name='certification image'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='personals/', verbose_name='personal image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 11, 31, 35, 12742, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
