# Generated by Django 5.1.6 on 2025-03-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_location_remove_barberprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.AlterModelOptions(
            name='unavailability',
            options={'ordering': ['id'], 'verbose_name': 'UnAvailability', 'verbose_name_plural': 'UnAvailability'},
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
        migrations.AlterModelTable(
            name='unavailability',
            table='unavailability',
        ),
    ]
