# Generated by Django 5.1.6 on 2025-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_location_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accept_status',
            field=models.PositiveSmallIntegerField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WAITING', 'waiting')], default=3, verbose_name='accept status'),
        ),
    ]
