# Generated by Django 5.1.6 on 2025-03-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_reservation_accept_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OffTimes',
            new_name='OffTime',
        ),
    ]
