# Generated by Django 5.1.6 on 2025-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_reservation_date_alter_unavailability_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accept_status',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('WAITING', 'waiting')], default='waiting', verbose_name='accept status'),
        ),
    ]
