# Generated by Django 5.1.6 on 2025-03-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='max_reservation_days',
            field=models.SmallIntegerField(default=7, verbose_name='max reservation days'),
        ),
        migrations.AddField(
            model_name='barber',
            name='reservation_gap',
            field=models.SmallIntegerField(default=30, verbose_name='reservation gap'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
