# Generated by Django 5.1.6 on 2025-03-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='barbers.barber'),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('barber', 'day')},
        ),
    ]
