# Generated by Django 5.1.6 on 2025-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_workday_barber_alter_workday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workday',
            constraint=models.UniqueConstraint(fields=('barber', 'day'), name='unique_barber_day'),
        ),
    ]
