# Generated by Django 5.1.6 on 2025-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_alter_workday_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offtime',
            old_name='day',
            new_name='workday',
        ),
    ]
