# Generated by Django 5.1.6 on 2025-03-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_rename_day_offtime_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offtime',
            name='end_time',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='offtime',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='offtime',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_times', to='barbers.workday'),
        ),
    ]
