# Generated by Django 5.1.6 on 2025-03-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_rename_accept_status_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('waiting', 'waiting')], default='waiting', verbose_name='status'),
        ),
    ]
